// Job Operations Module
// Adds job-related CRUD operations to DatabaseService

import logger from '../logger.js';

/**
 * Job operations mixin
 * Adds job-related methods to DatabaseService
 */
export function addJobOperations(DatabaseService) {
  /**
   * Create a new analysis job record
   * @param {Object} data - Job data
   * @returns {Promise<Object>} The created job
   */
  DatabaseService.prototype.createAnalysisJob = async function(data) {
    const id = data.id; // Usually generated by orchestrator
    const now = new Date().toISOString();
    
    try {
      await this.run(`
        INSERT INTO analysis_jobs (
          id, blueprint_id, job_type, status, progress, created_at
        ) VALUES (?, ?, ?, ?, ?, ?)
      `, [
        id,
        data.blueprintId || null,
        data.jobType || 'blueprint_analysis',
        data.status || 'pending',
        data.progress || 0,
        now
      ]);
      
      return await this.getAnalysisJob(id);
    } catch (error) {
      logger.error('Failed to create analysis job', { error: error.message, id });
      throw error;
    }
  };

  /**
   * Get an analysis job by ID
   * @param {string} id - Job ID
   * @returns {Promise<Object|null>}
   */
  DatabaseService.prototype.getAnalysisJob = async function(id) {
    try {
      const job = await this.get('SELECT * FROM analysis_jobs WHERE id = ?', [id]);
      if (job && job.result) {
        try { job.result = JSON.parse(job.result); } catch (e) {}
      }
      return job;
    } catch (error) {
      logger.error(`Error getting analysis job: ${id}`, { error: error.message });
      return null;
    }
  };

  /**
   * Get all analysis jobs with optional filtering
   * @param {Object} filters - Filter options (blueprintId, status, limit, offset)
   * @returns {Promise<Array>}
   */
  DatabaseService.prototype.getAllAnalysisJobs = async function(filters = {}) {
    let where = 'WHERE 1=1';
    const params = [];

    if (filters.blueprintId) {
      where += ' AND blueprint_id = ?';
      params.push(filters.blueprintId);
    }

    if (filters.status) {
      where += ' AND status = ?';
      params.push(filters.status);
    }

    try {
      let query = `SELECT * FROM analysis_jobs ${where} ORDER BY created_at DESC`;

      if (filters.limit) {
        query += ' LIMIT ?';
        params.push(parseInt(filters.limit));
        if (filters.offset) {
          query += ' OFFSET ?';
          params.push(parseInt(filters.offset));
        }
      }

      const jobs = await this.all(query, params);
      return jobs.map(job => {
        if (job.result) {
          try { job.result = JSON.parse(job.result); } catch (e) {}
        }
        return job;
      });
    } catch (error) {
      logger.error('Error getting all analysis jobs', { error: error.message, filters });
      return [];
    }
  };

  /**
   * Update an analysis job status and progress
   * @param {string} id - Job ID
   * @param {Object} data - Update data
   */
  DatabaseService.prototype.updateAnalysisJob = async function(id, data) {
    const fields = [];
    const params = [];
    const now = new Date().toISOString();

    if (data.status) {
      fields.push('status = ?');
      params.push(data.status);
      if (data.status === 'processing' && !data.started_at) {
        fields.push('started_at = ?');
        params.push(now);
      } else if ((data.status === 'completed' || data.status === 'failed') && !data.completed_at) {
        fields.push('completed_at = ?');
        params.push(now);
      }
    }

    if (data.progress !== undefined) {
      fields.push('progress = ?');
      params.push(data.progress);
    }

    if (data.result !== undefined) {
      fields.push('result = ?');
      params.push(typeof data.result === 'object' ? JSON.stringify(data.result) : data.result);
    }

    if (data.error !== undefined) {
      fields.push('error = ?');
      params.push(data.error);
    }

    if (fields.length === 0) return await this.getAnalysisJob(id);

    params.push(id);

    try {
      const result = await this.run(`
        UPDATE analysis_jobs SET ${fields.join(', ')}
        WHERE id = ?
      `, params);
      
      if (result.changes === 0) return null;
      return await this.getAnalysisJob(id);
    } catch (error) {
      logger.error(`Failed to update analysis job: ${id}`, { error: error.message });
      throw error;
    }
  };

  /**
   * Delete old analysis jobs
   * @param {number} days - Delete jobs older than X days
   */
  DatabaseService.prototype.cleanupAnalysisJobs = async function(days = 30) {
    try {
      const result = await this.run(`
        DELETE FROM analysis_jobs 
        WHERE created_at < datetime('now', ?)
      `, [`-${days} days`]);
      return result.changes;
    } catch (error) {
      logger.error('Failed to cleanup analysis jobs', { error: error.message });
      return 0;
    }
  };
}

export default addJobOperations;
