import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';
import {
  Download, FileText, DollarSign, Package, BarChart3, Printer
} from 'lucide-react';

const CATEGORY_LABELS = {
  pipe: 'Pipe',
  fittings: 'Fittings',
  fixtures: 'Fixtures',
  valves: 'Valves',
  water_heater: 'Water Heaters',
  gas: 'Gas',
  misc: 'Miscellaneous',
  uncategorized: 'Other'
};

export default function TakeoffReport({ takeoffId, takeoffName }) {
  const [sortBy, setSortBy] = useState('category');

  const { data: summaryData, isLoading, error } = useQuery({
    queryKey: ['takeoff-summary', takeoffId],
    queryFn: () => api.takeoff.getSummary(takeoffId),
    enabled: !!takeoffId
  });

  const summary = summaryData || {};
  const items = summary.items || [];
  const grandTotal = summary.grandTotal || 0;

  // Sort items
  const sortedItems = [...items].sort((a, b) => {
    if (sortBy === 'category') return (a.materialCategory || '').localeCompare(b.materialCategory || '');
    if (sortBy === 'cost') return b.totalCost - a.totalCost;
    if (sortBy === 'name') return (a.materialName || '').localeCompare(b.materialName || '');
    return 0;
  });

  // Group by category for display
  const grouped = sortedItems.reduce((acc, item) => {
    const cat = item.materialCategory || 'uncategorized';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(item);
    return acc;
  }, {});

  const exportCSV = () => {
    const rows = [
      ['Material', 'Category', 'Quantity', 'Unit', 'Unit Cost', 'Total Cost']
    ];

    sortedItems.forEach(item => {
      rows.push([
        item.materialName,
        CATEGORY_LABELS[item.materialCategory] || item.materialCategory,
        item.totalQuantity.toFixed(2),
        item.unit,
        item.unitCost.toFixed(2),
        item.totalCost.toFixed(2)
      ]);
    });

    rows.push([]);
    rows.push(['', '', '', '', 'Grand Total:', grandTotal.toFixed(2)]);

    const csv = rows.map(r => r.map(c => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `takeoff-${takeoffName || takeoffId}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const exportPDF = async () => {
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Material Takeoff Report', 14, 22);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('CTL Plumbing LLC - DFW Metroplex', 14, 30);
      doc.text(`Report: ${takeoffName || 'Untitled Takeoff'}`, 14, 36);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 42);
      doc.text(`Items: ${summary.itemCount || 0}`, 14, 48);

      // Separator
      doc.setDrawColor(200);
      doc.line(14, 52, 196, 52);

      // Table headers
      let y = 60;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text('Material', 14, y);
      doc.text('Category', 80, y);
      doc.text('Qty', 120, y);
      doc.text('Unit', 138, y);
      doc.text('Unit Cost', 155, y);
      doc.text('Total', 180, y);

      doc.setDrawColor(200);
      doc.line(14, y + 2, 196, y + 2);
      y += 8;

      // Table rows
      doc.setFont('helvetica', 'normal');
      sortedItems.forEach(item => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(String(item.materialName || '').substring(0, 35), 14, y);
        doc.text(String(CATEGORY_LABELS[item.materialCategory] || item.materialCategory || ''), 80, y);
        doc.text(item.totalQuantity.toFixed(1), 120, y);
        doc.text(String(item.unit || ''), 138, y);
        doc.text(`$${item.unitCost.toFixed(2)}`, 155, y);
        doc.text(`$${item.totalCost.toFixed(2)}`, 180, y);
        y += 6;
      });

      // Total
      y += 4;
      doc.setDrawColor(100);
      doc.line(14, y, 196, y);
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Grand Total:', 140, y);
      doc.text(`$${grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 180, y);

      // Footer
      y += 20;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(150);
      doc.text('Generated by Opensite - CTL Plumbing Intelligence Platform', 14, y);

      doc.save(`takeoff-${takeoffName || takeoffId}.pdf`);
    } catch (err) {
      console.error('PDF export error:', err);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (!takeoffId) {
    return (
      <div className="card text-center py-12">
        <FileText className="w-12 h-12 mx-auto mb-3 text-gray-300" />
        <p className="text-gray-500">Select or create a takeoff to view the report</p>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="card">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-gray-200 rounded w-1/3"></div>
          <div className="h-4 bg-gray-200 rounded w-1/4"></div>
          <div className="space-y-2">
            {[1, 2, 3, 4, 5].map(i => (
              <div key={i} className="h-10 bg-gray-200 rounded"></div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="card bg-red-50 border-red-200 text-red-700 text-center py-8">
        <p>Failed to load takeoff report: {error.message}</p>
      </div>
    );
  }

  return (
    <div className="space-y-4" id="takeoff-report">
      {/* Report Header */}
      <div className="card">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xl font-bold text-gray-900">{takeoffName || 'Takeoff Report'}</h3>
            <p className="text-sm text-gray-500 mt-1">
              {summary.itemCount || 0} line items &middot; Generated {new Date().toLocaleDateString()}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
              className="input text-sm py-1"
            >
              <option value="category">Sort by Category</option>
              <option value="cost">Sort by Cost</option>
              <option value="name">Sort by Name</option>
            </select>
            <button
              onClick={handlePrint}
              className="btn-secondary flex items-center gap-2 text-sm"
              title="Print"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              onClick={exportCSV}
              className="btn-secondary flex items-center gap-2 text-sm"
              title="Export CSV"
            >
              <Download className="w-4 h-4" />
              CSV
            </button>
            <button
              onClick={exportPDF}
              className="btn-primary flex items-center gap-2 text-sm"
              title="Export PDF"
            >
              <Download className="w-4 h-4" />
              PDF
            </button>
          </div>
        </div>
      </div>

      {/* Grand Total Card */}
      <div className="card bg-primary-50 border-primary-200">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center">
            <DollarSign className="w-6 h-6 text-primary-600" />
          </div>
          <div>
            <p className="text-sm text-primary-700">Grand Total</p>
            <p className="text-3xl font-bold text-primary-900">
              ${grandTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </p>
          </div>
          <div className="ml-auto text-right">
            <p className="text-sm text-primary-700">{items.length} materials</p>
            <p className="text-sm text-primary-700">{summary.itemCount || 0} line items</p>
          </div>
        </div>
      </div>

      {/* Material Table by Category */}
      {items.length === 0 ? (
        <div className="card text-center py-12">
          <Package className="w-12 h-12 mx-auto mb-3 text-gray-300" />
          <p className="text-gray-500">No items in this takeoff yet</p>
          <p className="text-sm text-gray-400 mt-1">Add measurements and assign materials to generate a report</p>
        </div>
      ) : (
        <div className="space-y-4">
          {Object.entries(grouped).map(([category, categoryItems]) => {
            const categoryTotal = categoryItems.reduce((sum, i) => sum + i.totalCost, 0);

            return (
              <div key={category} className="card">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="font-semibold text-gray-900 flex items-center gap-2">
                    <BarChart3 className="w-4 h-4 text-primary-600" />
                    {CATEGORY_LABELS[category] || category}
                  </h4>
                  <span className="font-semibold text-gray-700">
                    ${categoryTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </span>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-gray-200">
                        <th className="text-left py-2 px-2 text-gray-500 font-medium">Material</th>
                        <th className="text-right py-2 px-2 text-gray-500 font-medium">Quantity</th>
                        <th className="text-center py-2 px-2 text-gray-500 font-medium">Unit</th>
                        <th className="text-right py-2 px-2 text-gray-500 font-medium">Unit Cost</th>
                        <th className="text-right py-2 px-2 text-gray-500 font-medium">Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      {categoryItems.map((item, idx) => (
                        <tr key={idx} className="border-b border-gray-50 hover:bg-gray-50">
                          <td className="py-2 px-2 text-gray-900">{item.materialName}</td>
                          <td className="py-2 px-2 text-right text-gray-700">
                            {item.totalQuantity.toFixed(item.unit === 'ea' ? 0 : 1)}
                          </td>
                          <td className="py-2 px-2 text-center text-gray-500">{item.unit}</td>
                          <td className="py-2 px-2 text-right text-gray-700">
                            ${item.unitCost.toFixed(2)}
                          </td>
                          <td className="py-2 px-2 text-right font-medium text-gray-900">
                            ${item.totalCost.toFixed(2)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
